# Generated by Django 2.1.5 on 2019-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default='你猜', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_type',
            field=models.CharField(default='不详', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='petname',
            field=models.CharField(default='不详', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default='太帅无法显示', max_length=1024),
        ),
    ]
