# Generated by Django 2.1.5 on 2019-03-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_resetpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='user',
            new_name='email',
        ),
    ]
