# Generated by Django 2.1.5 on 2019-03-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190321_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='email',
            new_name='user',
        ),
    ]
