# Generated by Django 2.1.5 on 2019-03-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190321_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
