# Generated by Django 2.1.5 on 2019-03-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190321_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmstring',
            name='type',
            field=models.CharField(default='No', max_length=256),
        ),
    ]
