# Generated by Django 2.1.5 on 2019-03-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_confirmstring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
