# Generated by Django 2.1.5 on 2019-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20190328_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(default='太帅无法显示', max_length=1024),
        ),
    ]
