# Generated by Django 2.1.5 on 2019-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190329_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to='photo/'),
        ),
    ]
