# Generated by Django 2.1.5 on 2019-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190329_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='img/default.jpg', null=True, upload_to='photo/'),
        ),
    ]
