# Generated by Django 2.1.5 on 2019-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190330_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/default.png', null=True, upload_to='photo/'),
        ),
    ]
