# Generated by Django 2.1.5 on 2019-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20190330_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photo/default.png', null=True, upload_to='photo/'),
        ),
    ]
