# Generated by Django 2.1.5 on 2019-04-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190330_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
