# Generated by Django 2.1.5 on 2019-04-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('uname', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('ctype', models.CharField(max_length=200)),
                ('cdescribe', models.TextField(null=True)),
                ('cnumber', models.IntegerField(default=0, null=True)),
                ('cpath', models.CharField(default='ooo/path/ii.jpg', max_length=200, null=True)),
                ('ctime', models.CharField(max_length=200, null=True)),
                ('ctypeid', models.IntegerField(null=True)),
                ('csparestr', models.CharField(max_length=200, null=True)),
                ('cdesc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('ptype', models.CharField(max_length=200)),
                ('pdescribe', models.TextField(null=True)),
                ('pnumber', models.IntegerField(default=0, null=True)),
                ('ppath', models.CharField(default='ooo/path/ii.jpg', max_length=200, null=True)),
                ('ptime', models.CharField(max_length=200, null=True)),
                ('ptypeid', models.IntegerField(null=True)),
                ('pspareint', models.IntegerField(null=True)),
                ('psparestr', models.CharField(max_length=200, null=True)),
                ('pdesc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=100)),
                ('Pdescribe', models.CharField(max_length=225)),
                ('Pprice', models.FloatField()),
                ('Ptime', models.CharField(max_length=100)),
                ('Ptype', models.CharField(max_length=100)),
                ('Pamount', models.IntegerField()),
                ('Pphoto', models.CharField(max_length=200)),
            ],
        ),
    ]
