# Generated by Django 2.1.5 on 2019-04-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('main', models.CharField(max_length=4096)),
                ('time', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=80)),
                ('pet_type', models.CharField(max_length=120)),
                ('pic', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Find_pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('main', models.CharField(max_length=4096)),
                ('time', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=80)),
                ('thanks', models.CharField(max_length=120)),
                ('pic', models.CharField(max_length=80)),
            ],
        ),
    ]
