# Generated by Django 2.1.5 on 2019-04-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('bbs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=30)),
                ('pdate', models.DateTimeField()),
                ('ptype', models.CharField(max_length=200)),
                ('psex', models.CharField(max_length=20)),
                ('page', models.IntegerField()),
                ('pintro', models.TextField()),
                ('pwords', models.TextField()),
            ],
        ),
    ]
