# Generated by Django 2.1.5 on 2019-04-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs',
            options={'ordering': ['pub_date'], 'verbose_name': '用户'},
        ),
        migrations.RenameField(
            model_name='bbs',
            old_name='bbs',
            new_name='ubbs',
        ),
    ]
